Modify build workflow to improve package listing
Updated commands to list packages and show current directory.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -222,10 +222,10 @@ jobs:
         run: |
           echo "#TODO"
           echo "Builded packages:"
-          ls -la /tmp/xut-repos/_void-linux_void-packages/hostdir/binpkgs/ || echo "Directory not found"
+          ls /tmp/xut-repos/_void-linux_void-packages/hostdir/binpkgs/ || echo "Directory not found"
           echo
-          echo "Directory tree"
-          tree -d
+          echo "Current directory:"
+          pwd
           echo
           echo "/tmp Directory tree"
           cd /tmp
